"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
crypto features are by default exposed.

#### Granted Permissions

It allows access to all crypto commands.
"""
permissions = ["allow-generate", "allow-exists", "allow-get-public-key", "allow-sign-payload", "allow-verify-signature"]